version: "3.9"


services:
    gateway:
        build: ./docker/gateway
        volumes:
            - ./:/app:delegated
            - ./docker/gateway/config/conf.d:/etc/nginx/conf.d
        ports:
            - "${GATEWAY_PORT}:80"
        environment:
            XDEBUG_CONFIG: remote_host=host.docker.internal
            IS_DOCKER: 'yes'
        networks:
            - default

    app:
        build: ./docker
        hostname: app
        volumes:
            - ./:/app:delegated
        environment:
            XDEBUG_CONFIG: remote_host=host.docker.internal
            IS_DOCKER: 'yes'
        networks:
            - default

    db:
        hostname: db
        build: ./docker/db
        volumes:
            - ./docker/init:/docker-entrypoint-initdb.d
            - ./docker/db/files:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: p@$$word
            MYSQL_DATABASE: app
        networks:
            - default
